### PR TITLE
Fixes for 1.0

### PR DESCRIPTION
**Pull request by miguelraz**
Eliminate deprecations
Update REQUIRE
Remove Compat

Fixing deprecations

Updated build files

### CODE REVIEW

**Comment by miguelraz** [comment]
Pinging @eschnett !
This is the result of an upgradathon for Julia 1.0 with amazing help by Scott P. Jones.
Any chance you can tag a release for 1.0?
Thank you!

**Comment by eschnett** [comment]
This removes support for Julia 0.5 and 0.6, requiring people to use at least Julia 0.7. Given that this version was only released a few days ago, I'd like to keep at least support for Julia 0.6 around.

**Comment by eschnett** [comment]
Actually, this will be fine, I will only have to release a new major version.

**Comment by miguelraz** [comment]
Recommended policy by core devs is:
If there are commits that haven't been released for v0.6, then those should be released and tagged accordingly.
Once those happen, forking into 1.0 is recommended, as people can continue using patched compatibility fixes.
Thanks for the prompt response!

**Comment by miguelraz** [comment]
Bump. Good to go?

**Comment by eschnett** [comment]
There is a conflict in `appveyor.yml`.

**Comment by miguelraz** [comment]
I've now [spliced the Tensors.jl](https://github.com/KristofferC/Tensors.jl/blob/master/.appveyor.yml) `.appveyor.yml` file for the old ValueSymbols one.
Tests pass locally.

**Comment by miguelraz** [comment]
Sorry, I am not understanding why there is a merge conflict when I am updating the entire `.appveyor.yml` file.
Although I believe @eschnett can just click for the selected patch.

**Comment by eschnett** [comment]
Did you start your changes from the current master or from an older version of the master branch? If you locally either merge the master branch, or rebase your changes onto the current master branch, then these conflicts should go away.

**Comment by miguelraz** [comment]
Ah yes, the classic "didn't notice I was upstreamed". 
Thanks for the tip!

**Pull request merged**
